apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: dev
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      imagePullSecrets:
        - name: nexus-registry-secret
      containers:
        - name: discovery-server
          image: nexus:8081/docker-hosted/dev/discovery-server:0.1.1
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8761
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
