apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  CONFIG_SERVER_URL: {{ .Values.config.configServerUrl }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive }}
