imageRegistry: nexus:8081/docker-hosted/dev
imagePullSecret: nexus-registry-secret
imagePullPolicy: Always
replicaCount: 1

config:
  configServerUrl: http://config-server:8888/
  springProfilesActive: docker

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

configServer:
  image: config-server
  tag: 0.1.1
  port: 8888
  healthPath: /

discoveryServer:
  image: discovery-server
  tag: 0.1.1
  port: 8761
  healthPath: /actuator/health

customersService:
  image: customers-service
  tag: 0.1.1
  port: 8081
  healthPath: /actuator/health

vetsService:
  image: vets-service
  tag: 0.1.1
  port: 8083
  healthPath: /actuator/health

visitsService:
  image: visits-service
  tag: 0.1.1
  port: 8082
  healthPath: /actuator/health

apiGateway:
  image: api-gateway
  tag: 0.1.1
  port: 8080
  healthPath: /actuator/health

ingress:
  enabled: true
  className: nginx
  path: /
